version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - gin_tamplate_data:/var/lib/postgresql/data

volumes:
  gin_tamplate_data:
    name: gin_tamplate_data